### ISSUE TITLE
Added dN_obs to model

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#10]
I've added dN_obs back in to the model, I think more data will help the model get a better handle on some of the parameters. I did this really quick and could not find the appropriate equations in those papers in the repo so you will need to look over the math/code and fix things up. This added more pars/priors so the histogram plot is now broken, I fixed up the rest of it though.

**Comment by yarimitsu** [comment]
Ok got it. I've been  thinking dN should go back in. I've got a meeting tomorrow but should be able to focus on it tomorrow afternoon. Ill get this back to you soon.
