### ISSUE TITLE
omega bit

### ISSUE THREAD

**Issue by yarimitsu** [quantifish/isotope#19]
ok so there is this paper I will put in the general  doc folder (not the one in Yumi). But here is where this omega part comes from. The mean part is akin to what I did outside of the model (would be happy to do that again if it makes you feel better) with tau_g and dH_w_g...

The reason it was in there as mean(omega[G] * dH_w_g) is because the model wouldn't run when I took mean out. In LaPlaces Demon I thought it was a vector vs. scalar issue. Was always planning to deal with it later...which is now.

![image](https://cloud.githubusercontent.com/assets/13755255/9537052/5101fc56-4ce0-11e5-9291-172fc3a44151.png)

**Comment by quantifish** [comment]
OK, still not entirely clear to me as no indices on their eqns. But I think what they are saying is for each species they have an omega_j, but how many dH_w's do they have? Maybe they just have 1? Thus perhaps our eqn should be 

omega[g] * mean(dH_w_g)????

**Comment by yarimitsu** [comment]
why does it have to be mean of anything? Why doesn't it work like this:
omega[g] * dH_w_g[g]

**Comment by quantifish** [comment]
I dunno

**Comment by quantifish** [comment]
Haha Ill try it

**Comment by quantifish** [comment]
OK, back to you Yumi. You'll wanna get all the plotting updated to suit the new model structure now. I've changed the names of a few things, added in sigma_omega, changed the omega stuff about. Take a look and see what you reckon. Once you get the plots sorted lets take a look and maybe have a chat about it.
