### ISSUE TITLE
CLR transform

### ISSUE THREAD

**Issue by yarimitsu** [quantifish/isotope#2]
how do you avoid using a for loop to assign phis for each group in the CLR transform section? OR how do you use a for loop to to do this? Could switch back to dirichlet for phis to avoid the CLR transform, but this must be easier than I'm making it.

**Comment by quantifish** [comment]
I think that before we go ahead with all of the complex groupings etc we should get what we have at the moment working properly, along with all of the plots that we need to interpret the model...

**Comment by quantifish** [comment]
Just as a rule of thumb, don't push something to GitHub if it is broken, it took me a while to get your code working again, I needed to revert back to the old version in order to do so.

**Comment by yarimitsu** [comment]
Whoops, sorry about that...I thought for some reason changes would need to be "approved" to be updated. OK I see that making this thing work, and getting plots worked out is important. So will do that now. THANKS
