### ISSUE TITLE
Lines 50 and 51

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#3]
The Specs that you are setting below does not run on my computer:

                     Specs = list(alpha.star = .234, B = NULL))

Does this not work on your machine if using:

                     Specs = list(alpha.star = .234))

**Comment by yarimitsu** [comment]
This does not run on my machine
  Specs = list(alpha.star = .234))
but this does (which is why I keep changing it back: 
  Specs = list(alpha.star = .234, B = NULL))

**Comment by quantifish** [comment]
OK, what version of LaplacesDemon do you have installed on your machine? I will make sure I get the same version so we are working off exactly the same thing.

**Comment by yarimitsu** [comment]
15.03.19 is the version I'm using. I'll check on the website now to see if there's an update.

**Comment by quantifish** [comment]
Works on my machine now
