### ISSUE TITLE
Need some automated plotting routines

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#4]
It would be good to have some automated plotting routines set up so that each time we run the model we can automatically generate a bunch of plots. These would help us interpret the model fit and make improvements where they are needs. Plots might include:

- [x] MCMC trace plots of each parameter
- [x] Histograms of each parameter with the associated prior plotted as a line
- [ ] plots of the data
- [x] plots or the model fit to the data

**Comment by quantifish** [comment]
I've made a start on this so you have something to work off/copy. See the file Yumi/Plot.R

**Comment by quantifish** [comment]
I think the next step should be for the Plot.R file to be fleshed out so that it contains all of the plots suggested above (and any others that you think are important to interpret the results).

**Comment by yarimitsu** [comment]
Oh man I hope I didn't screw it up again :). Yesterday I was like "if every learning curve were just about what icon to click..." hahaha. Apparently it isn't as straight forward as I thought.

Plot.R works at the moment so sending that ahead now. 

I'll keep working on data plots (phi pdfs, data plots in source isospace)

**Comment by yarimitsu** [comment]
this doesn't look right...what's going on here?
![2var](https://cloud.githubusercontent.com/assets/13755255/9236425/485e264c-40f1-11e5-85bc-271d8f3e6407.png)

**Comment by quantifish** [comment]
Don't worry too much that things don't look right at the moment. It will get there.

**Comment by quantifish** [comment]
Plots are looking good. Some suggestions:

- [ ] reduce the white space in trace plots though. Use the par(mar = ...) thingy in R
- [ ] remove red density lines from 4liklihood plot
- [ ] remove density line from 5phi plot and replace with the prior as in other plots
- [ ] same as above for 6sigma
- [ ] use las=1 on plot 7 so that y axis labels are horizontal
- [ ] repeat plots 7 using points in different color/shape as well (good to see both)

**Comment by yarimitsu** [comment]
Will remove the density lines, but can't do prior lines on 5phi because those values result from the back transformed CLR thing. However, the top 3 panels in 3phimod_fractionation shows the phi_mod parameters with their uniform priors. 

likewise, there are no priors on sigma_C or sigma_H, or the mixtures  u_C and u_H (i.e., expected mean values), these are all just monitored variables

**Comment by quantifish** [comment]
Right you are. In that case, just remove the density lines from histograms. It would be useful to come up with an informative naming convention for plot names. Normally I go with something like "mcmc_name.png" for MCMC type plots, and "data_name.png" for data only plots, and "fit_name.png" for model fits to data. You could take the MCMC plots a step further and go "mcmc_par_name.png" for those plots that are actually model parameters and "mcmc_mon_name.png" for monitored variables. Just a thought but it will help when trolling through plots.

**Comment by quantifish** [comment]
I'd suggest another MCMC plot showing the monitored phi's (i.e. the phis that all add up to 1). The priors on your plot that currently show the phi's dont make sense as the posterior is exceeding the prior bounds. I am taking a look at the model now.

**Comment by quantifish** [comment]
Oh I just noticed that plot is already there.

**Comment by quantifish** [comment]
What's with the NUTS naming convention?
