### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#6]
sigma_C <- sqrt(phi_M*phi_M*(var[1] + var[7]) + phi_F*phi_F*(var[2] + var[7]) + phi_C*phi_C*(var[3] + var[7]))

If yes then why not use

        sigma_C <- sqrt(phi_M^2*(var[1] + var[7]) + phi_F^2*(var[2] + var[7]) + phi_C^2*(var[3] + var[7]))

**Comment by yarimitsu** [comment]
Yes that's right. Can't remember why I did that but must have been it wouldn't run with the '^2'

From Semmens et al 2009:
![image](https://cloud.githubusercontent.com/assets/13755255/9279796/651e8c10-4266-11e5-8b0d-ebdfe78781d4.png)
