### ISSUE TITLE
Not working very well

### ISSUE THREAD

**Issue by quantifish** [quantifish/isotope#7]
OK, so I've decided that this aint working all that well and that we should change tact a little. I think that a lot of the problems are arising because of the phi parameters. The clr transform appears to be a load of crap and I'm not happy with the alternative. I'm going to do something a bit trickier, namely unit simplex transformation. Don't worry too much about the details, but it pretty much constrains our phi's to sum to 1 using well defined math.

I am going to write up the model in STAN called from within R. I recommend you install STAN, I'll write the model and get it running, then we can both run/improve the model. The STAN manual is an excellent reference material for Bayesian analyses as well, you should download a copy of that. Sorry this is taking a little longer than expected to get up and running Yumi.

**Comment by quantifish** [comment]
OK so I am really surprised at how well STAN performed. However, the model is suggesting that there is very little information about the parameters in the data.

**Comment by quantifish** [comment]
OK, gotta finish up for the day, what you could do is get all the plots that you have made working for the new model and double check the isotope.stan model is all specified as it should be (i.e. double check the math). Perhaps save a copy of that new plot that I made and put the code in the Plots.R file. Make sure that we have good plots showing the observed and expected model fits. Once that's done lets take one more look before progressing to adding more stuff in to the model. We can talk this weekend if you like?

**Comment by yarimitsu** [comment]
I don't know what to say, except you are a super hero. I'll totally get behind you and say that CLR transform is junk...but this is definitely going to rock the Bayesian isotope people so I better read up on wtf the simplex transform does.

At the moment I can't get the stan model running, so I'm going to work on that first (probably a windows thing). Then I'll work on plots.

**Comment by quantifish** [comment]
I wouldnt worry too much about the simplex thing, just understanding what it does is enough. Better off spending the time to get STAN working and learning some of the STAN basics. I've not used STAN before but I am impressed with how well it performed.

**Comment by yarimitsu** [comment]
got it working...hate Windows 64 bit. That is weirdly fast and mixed right away. Will look over stuff before I have to head out for the evening. The simplex thing is clever for sure.
